# -*- coding: utf-8 -*-
"""FACTORIAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z42wYvy7NljZ1etOwkHzis5p3y2c_ILU
"""

Factorial program

n = 5
fact = 1

for i in range(1, n + 1):
    fact *= i

print(f"Factorial of {n} = {fact}")